POST localhost:8081/api/order
Content-Type: application/json

{
  "orderLineItemsDtoList": [
    {
      "skuCode": "iphone_13",
      "price": 1200,
      "quantity": 1
    },
    {
      "skuCode": "iphone_13_red",
      "price": 1200,
      "quantity": 0
    }
  ]
}